// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5I63gFX9TRVNyk2bf-MME4NRx-rItnKo',
    appId: '1:896116234510:web:f163dd4f50c0efc0a39f5f',
    messagingSenderId: '896116234510',
    projectId: 'portis-66904',
    authDomain: 'portis-66904.firebaseapp.com',
    storageBucket: 'portis-66904.firebasestorage.app',
    measurementId: 'G-KJ77VB79ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHDwb_PiLZmZ27fXX1bqFzyY0Mz4oYAgA',
    appId: '1:896116234510:android:51c6046cf114845ea39f5f',
    messagingSenderId: '896116234510',
    projectId: 'portis-66904',
    storageBucket: 'portis-66904.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdPoLl2cBW46nI1y9_tN_Hs08UJsOUCz0',
    appId: '1:896116234510:ios:a2288f37b04686a8a39f5f',
    messagingSenderId: '896116234510',
    projectId: 'portis-66904',
    storageBucket: 'portis-66904.firebasestorage.app',
    iosBundleId: 'com.example.pcareApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdPoLl2cBW46nI1y9_tN_Hs08UJsOUCz0',
    appId: '1:896116234510:ios:a2288f37b04686a8a39f5f',
    messagingSenderId: '896116234510',
    projectId: 'portis-66904',
    storageBucket: 'portis-66904.firebasestorage.app',
    iosBundleId: 'com.example.pcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5I63gFX9TRVNyk2bf-MME4NRx-rItnKo',
    appId: '1:896116234510:web:ab6cf728ab457dfaa39f5f',
    messagingSenderId: '896116234510',
    projectId: 'portis-66904',
    authDomain: 'portis-66904.firebaseapp.com',
    storageBucket: 'portis-66904.firebasestorage.app',
    measurementId: 'G-VT801ZESKD',
  );
}
